### PR TITLE
Update ROADMAP.md

### PR DESCRIPTION
**Pull request by mflaxman10**
added to changes section, added export to Geopackage upcoming

### CODE REVIEW

**Review by tmostak — CHANGES_REQUESTED** [review]
Hi @mflaxman10, per our discussion, we should remove all Immerse/render related features from this, otherwise looks good!

**Review by mflaxman10 — COMMENTED** [review]
I'm hoping this is good now

**Comment by tmostak** [comment]
@mflaxman10 looks good... do you know how to squash into one commit (with a nice message)? If not not a big deal.

**Comment by mflaxman10** [comment]
I’m not authorized to merge the PR… can you do on your end?  Or I can ask to be given permissions, but don’t immediately have them.

**Pull request merged**
